export const INDONESIAN_PROVINCES = [
  'Aceh',
  'Bali',
  'Banten',
  'Daerah Istimewa Yogyakarta',
  'Daerah Khusus Ibukota Jakarta',
  'Gorontalo',
  'Jambi, Bengkulu',
  'Jawa Barat',
  'Jawa Tengah',
  'Jawa Timur',
  'Kalimantan Barat',
  'Kalimantan Selatan',
  'Kalimantan Tengah',
  'Kalimantan Timur',
  'Kalimantan Utara',
  'Kepulauan Bangka Belitung',
  'Kepulauan Riau',
  'Lampung',
  'Maluku',
  'Maluku Utara',
  'Nusa Tenggara Barat',
  'Nusa Tenggara Timur',
  'Papua',
  'Papua Barat',
  'Riau',
  'Sulawesi Barat',
  'Sulawesi Selatan',
  'Sulawesi Tengah',
  'Sulawesi Tenggara',
  'Sulawesi Utara',
  'Sumatera Barat',
  'Sumatera Selatan',
  'Sumatera Utara',
];

export const TURKISH_PROVINCES = [
  'Adana',
  'Adıyaman',
  'Antakya',
  'Batman',
  'Diyarbakır',
  'Elazığ',
  'Gaziantep',
  'Kahramanmaraş',
  'Kayseri',
  'Kilis',
  'Malatya',
  'Mardin',
  'Mersin',
  'Nevşehir',
  'Niğde',
  'Osmaniye',
  'Siirt',
];

export const EDUCATION_LEVEL = [
  'D1',
  'D2',
  'D3',
  'Prep Arab',
  'Prep Inggris',
  'Prep TÖMER',
  'S1',
  'S2',
  'S3',
  'SMA',
];

export const FACULTIES = [
  'Arsitektur',
  'Bisnis',
  'Ekonomi',
  'Farmasi',
  'Hukum',
  'Ilmu Komunikasi',
  'Ilmu Politik',
  'Kedokteran',
  'Kedokteran Gigi',
  'Kedokteran Hewan',
  'Keguruan',
  'Keperawatan',
  'Matematika Dan Ilmu Pengetahuan Alam',
  'Pariwisata',
  'Pendidikan',
  'Pertanian',
  'Psikologi',
  'Sastra Dan Humaniora',
  'Seni Rupa',
  'Sosial',
  'Teknik',
  'Teologi',
];

export const JALUR = [
  'Beasiswa',
  'Mandiri Agen',
  'Mandiri Tanpa Agen',
  'TDV',
  'YTB',
  'Yayasan',
];

export const INSTITUTIONS = [
  'Abdullah Gül University',
  'Adana Alparslan Türkeş University of Science and Technology',
  'Adıyaman University',
  'Batman University',
  'Cappadocia University',
  'Çağ University',
  'Çukurova University',
  'Dicle University',
  'Erciyes University',
  'Fırat University',
  'Gaziantep University',
  'Gaziantep University of Science and Technology',
  'Hasan Kalyoncu University',
  'Imam Hatip',
  'İnönü University',
  'Kahramanmaraş Sütçüimam University',
  'Kahramanmaraş İstiklal University',
  'Kayseri University',
  'Kilis 7 Aralık University',
  'Malatya Turgut Özal University',
  'Mardin Artuklu University',
  'Nevşehir Hacı Bektaş Veli University',
  'Nuh Naci Yazgan University',
  'Osmaniye Korkut Ata University',
  'Ömer Halisdemir University',
  'Sanko University',
  'Siirt University',
  'Süleymaniye',
  'Tarsus University',
  'Toros University',
  'Mersin University',
];
